<script>
  import * as Icon from '$lib/index.js';
  import DarkMode from 'flowbite-svelte/DarkMode.svelte';
  const random_tailwind_color = () => {
    const colors = ['red', 'yellow', 'green', 'blue', 'indigo', 'purple', 'pink'];
    const shades = ['300', '400', '500'];
    const randomColor = colors[Math.floor(Math.random() * colors.length)];
    const randomShade = shades[Math.floor(Math.random() * shades.length)];
    return `text-${randomColor}-${randomShade} dark:text-${randomColor}-${randomShade} inline m-1`;
  };
</script>

<DarkMode />
<div class="p-8">
  <Icon.AdjustmentsHorizontalOutline size="md" class={random_tailwind_color()} />
  <Icon.AdjustmentsVerticalOutline size="md" class={random_tailwind_color()} />
  <Icon.AdressBookOutline size="md" class={random_tailwind_color()} />
  <Icon.AlignCenterOutline size="md" class={random_tailwind_color()} />
  <Icon.AngleDownOutline size="md" class={random_tailwind_color()} />
  <Icon.AngleLeftOutline size="md" class={random_tailwind_color()} />
  <Icon.AngleRightOutline size="md" class={random_tailwind_color()} />
  <Icon.AngleTopOutline size="md" class={random_tailwind_color()} />
  <Icon.AnnotationOutline size="md" class={random_tailwind_color()} />
  <Icon.ArchiveOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowDownOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowDownToBracketOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowLeftOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowLeftToBracketOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowRightArrowLeftOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowRightOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowRightToBracketOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowSortLettersOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowUpDownOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowUpOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowUpRightFromSquareOutline size="md" class={random_tailwind_color()} />
  <Icon.ArrowsRepeat1Outline size="md" class={random_tailwind_color()} />
  <Icon.ArrowsRepeatOutline size="md" class={random_tailwind_color()} />
  <Icon.AtomOutline size="md" class={random_tailwind_color()} />
  <Icon.BackwardStepOutline size="md" class={random_tailwind_color()} />
  <Icon.BadgeCheckOutline size="md" class={random_tailwind_color()} />
  <Icon.BarsOutline size="md" class={random_tailwind_color()} />
  <Icon.BellActiveAltOutline size="md" class={random_tailwind_color()} />
  <Icon.BellActiveOutline size="md" class={random_tailwind_color()} />
  <Icon.BellOutline size="md" class={random_tailwind_color()} />
  <Icon.BellRingOutline size="md" class={random_tailwind_color()} />
  <Icon.BlenderPhoneOutline size="md" class={random_tailwind_color()} />
  <Icon.BookOpenOutline size="md" class={random_tailwind_color()} />
  <Icon.BookOutline size="md" class={random_tailwind_color()} />
  <Icon.BookmarkOutline size="md" class={random_tailwind_color()} />
  <Icon.BrainOutline size="md" class={random_tailwind_color()} />
  <Icon.BriefcaseOutline size="md" class={random_tailwind_color()} />
  <Icon.BugOutline size="md" class={random_tailwind_color()} />
  <Icon.BullhornOutline size="md" class={random_tailwind_color()} />
  <Icon.CalendarEditOutline size="md" class={random_tailwind_color()} />
  <Icon.CalendarMonthOutline size="md" class={random_tailwind_color()} />
  <Icon.CalendarWeekOutline size="md" class={random_tailwind_color()} />
  <Icon.CameraFotoOutline size="md" class={random_tailwind_color()} />
  <Icon.CaptioningOutline size="md" class={random_tailwind_color()} />
  <Icon.CaretDownOutline size="md" class={random_tailwind_color()} />
  <Icon.CaretLeftOutline size="md" class={random_tailwind_color()} />
  <Icon.CaretRightOutline size="md" class={random_tailwind_color()} />
  <Icon.CaretSortOutline size="md" class={random_tailwind_color()} />
  <Icon.CaretUpOutline size="md" class={random_tailwind_color()} />
  <Icon.CartOutline size="md" class={random_tailwind_color()} />
  <Icon.CartPlusAltOutline size="md" class={random_tailwind_color()} />
  <Icon.CartPlusOutline size="md" class={random_tailwind_color()} />
  <Icon.CashOutline size="md" class={random_tailwind_color()} />
  <Icon.ChartLineUpOutline size="md" class={random_tailwind_color()} />
  <Icon.ChartMixedOutline size="md" class={random_tailwind_color()} />
  <Icon.ChartOutline size="md" class={random_tailwind_color()} />
  <Icon.ChartPieOutline size="md" class={random_tailwind_color()} />
  <Icon.CheckCircleOutline size="md" class={random_tailwind_color()} />
  <Icon.CheckOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronDoubleDownOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronDoubleLeftOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronDoubleRightOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronDoubleUpOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronDownOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronLeftOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronRightOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronSortOutline size="md" class={random_tailwind_color()} />
  <Icon.ChevronUpOutline size="md" class={random_tailwind_color()} />
  <Icon.ClapperboardPlayOutline size="md" class={random_tailwind_color()} />
  <Icon.ClipboardCheckOutline size="md" class={random_tailwind_color()} />
  <Icon.ClipboardListOutline size="md" class={random_tailwind_color()} />
  <Icon.ClipboardOutline size="md" class={random_tailwind_color()} />
  <Icon.ClockOutline size="md" class={random_tailwind_color()} />
  <Icon.CloseOutline size="md" class={random_tailwind_color()} />
  <Icon.CloudArrowUpOutline size="md" class={random_tailwind_color()} />
  <Icon.CodeBranchOutline size="md" class={random_tailwind_color()} />
  <Icon.CodeForkOutline size="md" class={random_tailwind_color()} />
  <Icon.CodeMergeOutline size="md" class={random_tailwind_color()} />
  <Icon.CodeOutline size="md" class={random_tailwind_color()} />
  <Icon.CodePullRequestOutline size="md" class={random_tailwind_color()} />
  <Icon.CogOutline size="md" class={random_tailwind_color()} />
  <Icon.CompressOutline size="md" class={random_tailwind_color()} />
  <Icon.ComputerSpeakerOutline size="md" class={random_tailwind_color()} />
  <Icon.CreditCardOutline size="md" class={random_tailwind_color()} />
  <Icon.DatabaseOutline size="md" class={random_tailwind_color()} />
  <Icon.DesktopPcOutline size="md" class={random_tailwind_color()} />
  <Icon.DnaOutline size="md" class={random_tailwind_color()} />
  <Icon.DollarOutline size="md" class={random_tailwind_color()} />
  <Icon.DotsHorizontalOutline size="md" class={random_tailwind_color()} />
  <Icon.DotsVerticalOutline size="md" class={random_tailwind_color()} />
  <Icon.DownloadOutline size="md" class={random_tailwind_color()} />
  <Icon.DrawSquareOutline size="md" class={random_tailwind_color()} />
  <Icon.EditOutline size="md" class={random_tailwind_color()} />
  <Icon.EnvelopeOpenOutline size="md" class={random_tailwind_color()} />
  <Icon.EnvelopeOutline size="md" class={random_tailwind_color()} />
  <Icon.EuroOutline size="md" class={random_tailwind_color()} />
  <Icon.ExclamationCircleOutline size="md" class={random_tailwind_color()} />
  <Icon.ExpandOutline size="md" class={random_tailwind_color()} />
  <Icon.EyeOutline size="md" class={random_tailwind_color()} />
  <Icon.EyeSlashOutline size="md" class={random_tailwind_color()} />
  <Icon.FaceExplodeOutline size="md" class={random_tailwind_color()} />
  <Icon.FaceGrinOutline size="md" class={random_tailwind_color()} />
  <Icon.FaceGrinStarsOutline size="md" class={random_tailwind_color()} />
  <Icon.FaceLaughOutline size="md" class={random_tailwind_color()} />
  <Icon.FileChartBarOutline size="md" class={random_tailwind_color()} />
  <Icon.FileCheckOutline size="md" class={random_tailwind_color()} />
  <Icon.FileCirclePlusOutline size="md" class={random_tailwind_color()} />
  <Icon.FileCloneOutline size="md" class={random_tailwind_color()} />
  <Icon.FileCodeOutline size="md" class={random_tailwind_color()} />
  <Icon.FileCopyOutline size="md" class={random_tailwind_color()} />
  <Icon.FileCsvOutline size="md" class={random_tailwind_color()} />
  <Icon.FileExportOutline size="md" class={random_tailwind_color()} />
  <Icon.FileImageOutline size="md" class={random_tailwind_color()} />
  <Icon.FileImportOutline size="md" class={random_tailwind_color()} />
  <Icon.FileLinesOutline size="md" class={random_tailwind_color()} />
  <Icon.FileMusicOutline size="md" class={random_tailwind_color()} />
  <Icon.FileOutline size="md" class={random_tailwind_color()} />
  <Icon.FilePasteOutline size="md" class={random_tailwind_color()} />
  <Icon.FilePdfOutline size="md" class={random_tailwind_color()} />
  <Icon.FilePenOutline size="md" class={random_tailwind_color()} />
  <Icon.FilePptOutline size="md" class={random_tailwind_color()} />
  <Icon.FileShieldOutline size="md" class={random_tailwind_color()} />
  <Icon.FileVideoOutline size="md" class={random_tailwind_color()} />
  <Icon.FileWordOutline size="md" class={random_tailwind_color()} />
  <Icon.FileZipOutline size="md" class={random_tailwind_color()} />
  <Icon.FilterOutline size="md" class={random_tailwind_color()} />
  <Icon.FingerprintOutline size="md" class={random_tailwind_color()} />
  <Icon.FireOutline size="md" class={random_tailwind_color()} />
  <Icon.FolderDuplicateOutline size="md" class={random_tailwind_color()} />
  <Icon.FolderOpenOutline size="md" class={random_tailwind_color()} />
  <Icon.FolderOutline size="md" class={random_tailwind_color()} />
  <Icon.FolderPlusOutline size="md" class={random_tailwind_color()} />
  <Icon.ForwardOutline size="md" class={random_tailwind_color()} />
  <Icon.ForwardStepOutline size="md" class={random_tailwind_color()} />
  <Icon.GiftBoxOutline size="md" class={random_tailwind_color()} />
  <Icon.GlobeOutline size="md" class={random_tailwind_color()} />
  <Icon.GridOutline size="md" class={random_tailwind_color()} />
  <Icon.GridPlusOutline size="md" class={random_tailwind_color()} />
  <Icon.HeadphonesOutline size="md" class={random_tailwind_color()} />
  <Icon.HeartOutline size="md" class={random_tailwind_color()} />
  <Icon.HomeOutline size="md" class={random_tailwind_color()} />
  <Icon.HourglassOutline size="md" class={random_tailwind_color()} />
  <Icon.ImageOutline size="md" class={random_tailwind_color()} />
  <Icon.InboxFullOutline size="md" class={random_tailwind_color()} />
  <Icon.InboxOutline size="md" class={random_tailwind_color()} />
  <Icon.InfoCircleOutline size="md" class={random_tailwind_color()} />
  <Icon.KeyboardOutline size="md" class={random_tailwind_color()} />
  <Icon.LandmarkOutline size="md" class={random_tailwind_color()} />
  <Icon.LayersOutline size="md" class={random_tailwind_color()} />
  <Icon.LetterBoldOutline size="md" class={random_tailwind_color()} />
  <Icon.LetterItalicOutline size="md" class={random_tailwind_color()} />
  <Icon.LetterUnderlineOutline size="md" class={random_tailwind_color()} />
  <Icon.LifeBuoyOutline size="md" class={random_tailwind_color()} />
  <Icon.LinkOutline size="md" class={random_tailwind_color()} />
  <Icon.ListMusicOutline size="md" class={random_tailwind_color()} />
  <Icon.ListOutline size="md" class={random_tailwind_color()} />
  <Icon.LockOpenOutline size="md" class={random_tailwind_color()} />
  <Icon.LockOutline size="md" class={random_tailwind_color()} />
  <Icon.MailBoxOutline size="md" class={random_tailwind_color()} />
  <Icon.MapLocationOutline size="md" class={random_tailwind_color()} />
  <Icon.MapPinOutline size="md" class={random_tailwind_color()} />
  <Icon.MessageCaptionOutline size="md" class={random_tailwind_color()} />
  <Icon.MessageDotsOutline size="md" class={random_tailwind_color()} />
  <Icon.MessagesOutline size="md" class={random_tailwind_color()} />
  <Icon.MicrophoneOutline size="md" class={random_tailwind_color()} />
  <Icon.MinimizeOutline size="md" class={random_tailwind_color()} />
  <Icon.MinusOutline size="md" class={random_tailwind_color()} />
  <Icon.MobilePhoneOutline size="md" class={random_tailwind_color()} />
  <Icon.MoonOutline size="md" class={random_tailwind_color()} />
  <Icon.NewspapperOutline size="md" class={random_tailwind_color()} />
  <Icon.OrdoredListOutline size="md" class={random_tailwind_color()} />
  <Icon.PaletteOutline size="md" class={random_tailwind_color()} />
  <Icon.PaperClipOutline size="md" class={random_tailwind_color()} />
  <Icon.PapperPlaneOutline size="md" class={random_tailwind_color()} />
  <Icon.PauseOutline size="md" class={random_tailwind_color()} />
  <Icon.PenNibOutline size="md" class={random_tailwind_color()} />
  <Icon.PenOutline size="md" class={random_tailwind_color()} />
  <Icon.PhoneOutline size="md" class={random_tailwind_color()} />
  <Icon.PlayOutline size="md" class={random_tailwind_color()} />
  <Icon.PlusOutline size="md" class={random_tailwind_color()} />
  <Icon.PrinterOutline size="md" class={random_tailwind_color()} />
  <Icon.ProfileCardOutline size="md" class={random_tailwind_color()} />
  <Icon.QuestionCircleOutline size="md" class={random_tailwind_color()} />
  <Icon.QuoteOutline size="md" class={random_tailwind_color()} />
  <Icon.ReceiptOutline size="md" class={random_tailwind_color()} />
  <Icon.RectangleListOutline size="md" class={random_tailwind_color()} />
  <Icon.ReplyAllOutline size="md" class={random_tailwind_color()} />
  <Icon.RocketOutline size="md" class={random_tailwind_color()} />
  <Icon.RotateOutline size="md" class={random_tailwind_color()} />
  <Icon.RuleCombinedOutline size="md" class={random_tailwind_color()} />
  <Icon.SalePercentOutline size="md" class={random_tailwind_color()} />
  <Icon.ScaleBalancedOutline size="md" class={random_tailwind_color()} />
  <Icon.SearchOutline size="md" class={random_tailwind_color()} />
  <Icon.ShareAllOutline size="md" class={random_tailwind_color()} />
  <Icon.ShareNodesOutline size="md" class={random_tailwind_color()} />
  <Icon.ShieldOutline size="md" class={random_tailwind_color()} />
  <Icon.ShoppingBagOutline size="md" class={random_tailwind_color()} />
  <Icon.ShuffleOutline size="md" class={random_tailwind_color()} />
  <Icon.SortOutline size="md" class={random_tailwind_color()} />
  <Icon.StarHalfOutline size="md" class={random_tailwind_color()} />
  <Icon.StarHalfStrokeOutline size="md" class={random_tailwind_color()} />
  <Icon.StarOutline size="md" class={random_tailwind_color()} />
  <Icon.StoreOutline size="md" class={random_tailwind_color()} />
  <Icon.SunOutline size="md" class={random_tailwind_color()} />
  <Icon.SwatchbookOutline size="md" class={random_tailwind_color()} />
  <Icon.TableColumnOutline size="md" class={random_tailwind_color()} />
  <Icon.TableRowOutline size="md" class={random_tailwind_color()} />
  <Icon.TabletOutline size="md" class={random_tailwind_color()} />
  <Icon.TagOutline size="md" class={random_tailwind_color()} />
  <Icon.TerminalOutline size="md" class={random_tailwind_color()} />
  <Icon.ThumbsDownOutline size="md" class={random_tailwind_color()} />
  <Icon.ThumbsUpOutline size="md" class={random_tailwind_color()} />
  <Icon.TicketOutline size="md" class={random_tailwind_color()} />
  <Icon.TrashBinOutline size="md" class={random_tailwind_color()} />
  <Icon.TruckOutline size="md" class={random_tailwind_color()} />
  <Icon.UploadOutline size="md" class={random_tailwind_color()} />
  <Icon.UserAddOutline size="md" class={random_tailwind_color()} />
  <Icon.UserCircleOutline size="md" class={random_tailwind_color()} />
  <Icon.UserEditOutline size="md" class={random_tailwind_color()} />
  <Icon.UserHeadsetOutline size="md" class={random_tailwind_color()} />
  <Icon.UserOutline size="md" class={random_tailwind_color()} />
  <Icon.UserRemoveOutline size="md" class={random_tailwind_color()} />
  <Icon.UserSettingsOutline size="md" class={random_tailwind_color()} />
  <Icon.UsersGroupOutline size="md" class={random_tailwind_color()} />
  <Icon.UsersOutline size="md" class={random_tailwind_color()} />
  <Icon.VideoCameraOutline size="md" class={random_tailwind_color()} />
  <Icon.VolumeDownOutline size="md" class={random_tailwind_color()} />
  <Icon.VolumeUpOutline size="md" class={random_tailwind_color()} />
  <Icon.WalletOutline size="md" class={random_tailwind_color()} />
  <Icon.WandMagicSparklesOutline size="md" class={random_tailwind_color()} />
  <Icon.WindowOutline size="md" class={random_tailwind_color()} />
  <Icon.WindowRestoreOutline size="md" class={random_tailwind_color()} />
  <Icon.XCircleOutline size="md" class={random_tailwind_color()} />
  <Icon.ZoomInOutline size="md" class={random_tailwind_color()} />
  <Icon.ZoomOutOutline size="md" class={random_tailwind_color()} />
</div>
