<script>
  import * as Icon from '$lib';
  import DarkMode from 'flowbite-svelte/DarkMode.svelte';
  const random_tailwind_color = () => {
    const colors = ['primary', 'red', 'yellow', 'green', 'blue', 'indigo', 'purple', 'pink'];
    const shades = ['300', '400', '500'];
    const randomColor = colors[Math.floor(Math.random() * colors.length)];
    const randomShade = shades[Math.floor(Math.random() * shades.length)];
    return `text-${randomColor}-${randomShade} dark:text-${randomColor}-${randomShade} inline m-1`;
  };
</script>

<DarkMode />
<div class="p-8">
  <Icon.AddressCardSolid size="40" class={random_tailwind_color()} />
  <Icon.AdjustmentsHorizontalSolid size="40" class={random_tailwind_color()} />
  <Icon.AdjustmentsVerticalSolid size="40" class={random_tailwind_color()} />
  <Icon.AdressBookSolid size="40" class={random_tailwind_color()} />
  <Icon.AngleDownSolid size="40" class={random_tailwind_color()} />
  <Icon.AngleLeftSolid size="40" class={random_tailwind_color()} />
  <Icon.AngleRightSolid size="40" class={random_tailwind_color()} />
  <Icon.AngleUpSolid size="40" class={random_tailwind_color()} />
  <Icon.AnnotationSolid size="40" class={random_tailwind_color()} />
  <Icon.ArchiveSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowDownSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowDownToBraketSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowLeftSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowRightFromBracketSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowRightSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowRightToBracketSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowSortLettersSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowUpDownSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowUpRightSquareSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowUpSolid size="40" class={random_tailwind_color()} />
  <Icon.ArrowsRepeat1Solid size="40" class={random_tailwind_color()} />
  <Icon.ArrowsRepeatSolid size="40" class={random_tailwind_color()} />
  <Icon.AtomSolid size="40" class={random_tailwind_color()} />
  <Icon.BackwardStepSolid size="40" class={random_tailwind_color()} />
  <Icon.BadgeCheckSolid size="40" class={random_tailwind_color()} />
  <Icon.BagSolid size="40" class={random_tailwind_color()} />
  <Icon.BarsSolid size="40" class={random_tailwind_color()} />
  <Icon.BellActiveAltSolid size="40" class={random_tailwind_color()} />
  <Icon.BellActiveSolid size="40" class={random_tailwind_color()} />
  <Icon.BellRingSolid size="40" class={random_tailwind_color()} />
  <Icon.BellSolid size="40" class={random_tailwind_color()} />
  <Icon.BlenderPhoneSolid size="40" class={random_tailwind_color()} />
  <Icon.BoldSolid size="40" class={random_tailwind_color()} />
  <Icon.BookSolid size="40" class={random_tailwind_color()} />
  <Icon.BookmarkSolid size="40" class={random_tailwind_color()} />
  <Icon.BrainSolid size="40" class={random_tailwind_color()} />
  <Icon.BriefcaseSolid size="40" class={random_tailwind_color()} />
  <Icon.BugSolid size="40" class={random_tailwind_color()} />
  <Icon.BullhornSolid size="40" class={random_tailwind_color()} />
  <Icon.CalendarEditSolid size="40" class={random_tailwind_color()} />
  <Icon.CalendarMonthSolid size="40" class={random_tailwind_color()} />
  <Icon.CalendarWeekSolid size="40" class={random_tailwind_color()} />
  <Icon.CameraFotoSolid size="40" class={random_tailwind_color()} />
  <Icon.CaptioningSolid size="40" class={random_tailwind_color()} />
  <Icon.CaretDownSolid size="40" class={random_tailwind_color()} />
  <Icon.CaretLeftSolid size="40" class={random_tailwind_color()} />
  <Icon.CaretRightSolid size="40" class={random_tailwind_color()} />
  <Icon.CaretSortSolid size="40" class={random_tailwind_color()} />
  <Icon.CaretUpSolid size="40" class={random_tailwind_color()} />
  <Icon.CartPlusAltSolid size="40" class={random_tailwind_color()} />
  <Icon.CartPlusSolid size="40" class={random_tailwind_color()} />
  <Icon.CashSolid size="40" class={random_tailwind_color()} />
  <Icon.ChartLineDownSolid size="40" class={random_tailwind_color()} />
  <Icon.ChartLineUpSolid size="40" class={random_tailwind_color()} />
  <Icon.ChartMixedSolid size="40" class={random_tailwind_color()} />
  <Icon.ChartPieSolid size="40" class={random_tailwind_color()} />
  <Icon.ChartSolid size="40" class={random_tailwind_color()} />
  <Icon.CheckCircleSolid size="40" class={random_tailwind_color()} />
  <Icon.CheckSolid size="40" class={random_tailwind_color()} />
  <Icon.ChervonDoubleDownSolid size="40" class={random_tailwind_color()} />
  <Icon.ChervonDoubleLeftSolid size="40" class={random_tailwind_color()} />
  <Icon.ChervonDoubleRightSolid size="40" class={random_tailwind_color()} />
  <Icon.ChervonDoubleUpSolid size="40" class={random_tailwind_color()} />
  <Icon.ChevronDownSolid size="40" class={random_tailwind_color()} />
  <Icon.ChevronLeftSolid size="40" class={random_tailwind_color()} />
  <Icon.ChevronRightSolid size="40" class={random_tailwind_color()} />
  <Icon.ChevronSortSolid size="40" class={random_tailwind_color()} />
  <Icon.ChevronUpSolid size="40" class={random_tailwind_color()} />
  <Icon.ClapperboardPlaySolid size="40" class={random_tailwind_color()} />
  <Icon.ClipboardCheckSolid size="40" class={random_tailwind_color()} />
  <Icon.ClipboardListSolid size="40" class={random_tailwind_color()} />
  <Icon.ClipboardSolid size="40" class={random_tailwind_color()} />
  <Icon.ClockSolid size="40" class={random_tailwind_color()} />
  <Icon.CloneSolid size="40" class={random_tailwind_color()} />
  <Icon.CloseCircleSolid size="40" class={random_tailwind_color()} />
  <Icon.CloseSolid size="40" class={random_tailwind_color()} />
  <Icon.CloudArrowUpSolid size="40" class={random_tailwind_color()} />
  <Icon.CodeBranchSolid size="40" class={random_tailwind_color()} />
  <Icon.CodeForkSolid size="40" class={random_tailwind_color()} />
  <Icon.CodeMergeSolid size="40" class={random_tailwind_color()} />
  <Icon.CodePullRequestSolid size="40" class={random_tailwind_color()} />
  <Icon.CodeSolid size="40" class={random_tailwind_color()} />
  <Icon.CompressSolid size="40" class={random_tailwind_color()} />
  <Icon.ComputerSpeakerSolid size="40" class={random_tailwind_color()} />
  <Icon.CopySolid size="40" class={random_tailwind_color()} />
  <Icon.CotateSolid size="40" class={random_tailwind_color()} />
  <Icon.CreditCardSolid size="40" class={random_tailwind_color()} />
  <Icon.DatabaseSolid size="40" class={random_tailwind_color()} />
  <Icon.DesktopPcSolid size="40" class={random_tailwind_color()} />
  <Icon.DiscordSolid size="40" class={random_tailwind_color()} />
  <Icon.DnaSolid size="40" class={random_tailwind_color()} />
  <Icon.DollarSolid size="40" class={random_tailwind_color()} />
  <Icon.DownloadSolid size="40" class={random_tailwind_color()} />
  <Icon.DrawSquareSolid size="40" class={random_tailwind_color()} />
  <Icon.DribbbleSolid size="40" class={random_tailwind_color()} />
  <Icon.DropboxSolid size="40" class={random_tailwind_color()} />
  <Icon.EllipseHorizontalSolid size="40" class={random_tailwind_color()} />
  <Icon.EllipseVerticalSolid size="40" class={random_tailwind_color()} />
  <Icon.EnvelopeOpenSolid size="40" class={random_tailwind_color()} />
  <Icon.EnvelopeSolid size="40" class={random_tailwind_color()} />
  <Icon.EuroSolid size="40" class={random_tailwind_color()} />
  <Icon.ExclamationCircleSolid size="40" class={random_tailwind_color()} />
  <Icon.ExpandSolid size="40" class={random_tailwind_color()} />
  <Icon.EyeSlashSolid size="40" class={random_tailwind_color()} />
  <Icon.EyeSolid size="40" class={random_tailwind_color()} />
  <Icon.FaceGrinSolid size="40" class={random_tailwind_color()} />
  <Icon.FaceLaughSolid size="40" class={random_tailwind_color()} />
  <Icon.FaceMindBlowSolid size="40" class={random_tailwind_color()} />
  <Icon.FaceStarStruckSolid size="40" class={random_tailwind_color()} />
  <Icon.FacebookSolid size="40" class={random_tailwind_color()} />
  <Icon.FileChartBarSolid size="40" class={random_tailwind_color()} />
  <Icon.FileCheckSolid size="40" class={random_tailwind_color()} />
  <Icon.FileCodeSolid size="40" class={random_tailwind_color()} />
  <Icon.FileCopySolid size="40" class={random_tailwind_color()} />
  <Icon.FileCsvSolid size="40" class={random_tailwind_color()} />
  <Icon.FileEditSolid size="40" class={random_tailwind_color()} />
  <Icon.FileExportSolid size="40" class={random_tailwind_color()} />
  <Icon.FileImageSolid size="40" class={random_tailwind_color()} />
  <Icon.FileImportSolid size="40" class={random_tailwind_color()} />
  <Icon.FileLinesSolid size="40" class={random_tailwind_color()} />
  <Icon.FileMusicSolid size="40" class={random_tailwind_color()} />
  <Icon.FilePasteSolid size="40" class={random_tailwind_color()} />
  <Icon.FilePdfSolid size="40" class={random_tailwind_color()} />
  <Icon.FilePlusSolid size="40" class={random_tailwind_color()} />
  <Icon.FilePowerpointSolid size="40" class={random_tailwind_color()} />
  <Icon.FileShieldSolid size="40" class={random_tailwind_color()} />
  <Icon.FileSolid size="40" class={random_tailwind_color()} />

  <Icon.FileWordpressSolid size="40" class={random_tailwind_color()} />
  <Icon.FileZipperSolid size="40" class={random_tailwind_color()} />
  <Icon.FilterSolid size="40" class={random_tailwind_color()} />
  <Icon.FingerprintSolid size="40" class={random_tailwind_color()} />
  <Icon.FireSolid size="40" class={random_tailwind_color()} />
  <Icon.FolderDuplicateSolid size="40" class={random_tailwind_color()} />
  <Icon.FolderOpenSolid size="40" class={random_tailwind_color()} />
  <Icon.FolderPlusSolid size="40" class={random_tailwind_color()} />
  <Icon.FolderSolid size="40" class={random_tailwind_color()} />
  <Icon.ForwardSolid size="40" class={random_tailwind_color()} />
  <Icon.ForwardStepSolid size="40" class={random_tailwind_color()} />
  <Icon.GearSolid size="40" class={random_tailwind_color()} />
  <Icon.GiftBoxSolid size="40" class={random_tailwind_color()} />
  <Icon.GithubSolid size="40" class={random_tailwind_color()} />
  <Icon.GlobeSolid size="40" class={random_tailwind_color()} />
  <Icon.GoogleSolid size="40" class={random_tailwind_color()} />
  <Icon.GridPlusSolid size="40" class={random_tailwind_color()} />
  <Icon.GridSolid size="40" class={random_tailwind_color()} />
  <Icon.HeadphonesSolid size="40" class={random_tailwind_color()} />
  <Icon.HeartSolid size="40" class={random_tailwind_color()} />
  <Icon.HomeSolid size="40" class={random_tailwind_color()} />
  <Icon.HourglassSolid size="40" class={random_tailwind_color()} />
  <Icon.ImageSolid size="40" class={random_tailwind_color()} />
  <Icon.InboxFullSolid size="40" class={random_tailwind_color()} />
  <Icon.InboxSolid size="40" class={random_tailwind_color()} />
  <Icon.InfoCircleSolid size="40" class={random_tailwind_color()} />
  <Icon.ItalicSolid size="40" class={random_tailwind_color()} />
  <Icon.KeyboardSolid size="40" class={random_tailwind_color()} />
  <Icon.LandmarkSolid size="40" class={random_tailwind_color()} />
  <Icon.LayersSolid size="40" class={random_tailwind_color()} />
  <Icon.LifeBuoySolid size="40" class={random_tailwind_color()} />
  <Icon.LinkSolid size="40" class={random_tailwind_color()} />
  <Icon.LinkedinSolid size="40" class={random_tailwind_color()} />
  <Icon.ListMusicSolid size="40" class={random_tailwind_color()} />
  <Icon.ListOrdoredSolid size="40" class={random_tailwind_color()} />
  <Icon.ListSolid size="40" class={random_tailwind_color()} />
  <Icon.LockOpenSolid size="40" class={random_tailwind_color()} />
  <Icon.LockSolid size="40" class={random_tailwind_color()} />
  <Icon.MailBoxSolid size="40" class={random_tailwind_color()} />
  <Icon.MapPinAltSolid size="40" class={random_tailwind_color()} />
  <Icon.MapPinSolid size="40" class={random_tailwind_color()} />
  <Icon.MessageCaptionSolid size="40" class={random_tailwind_color()} />
  <Icon.MessagesSolid size="40" class={random_tailwind_color()} />
  <Icon.MicrophoneSolid size="40" class={random_tailwind_color()} />
  <Icon.MinimizeSolid size="40" class={random_tailwind_color()} />
  <Icon.MinusSolid size="40" class={random_tailwind_color()} />
  <Icon.MobilePhoneSolid size="40" class={random_tailwind_color()} />
  <Icon.MoonSolid size="40" class={random_tailwind_color()} />
  <Icon.NewspaperSolid size="40" class={random_tailwind_color()} />
  <Icon.OpenBookSolid size="40" class={random_tailwind_color()} />
  <Icon.PalleteSolid size="40" class={random_tailwind_color()} />
  <Icon.PapperClipSolid size="40" class={random_tailwind_color()} />
  <Icon.PapperPlaneSolid size="40" class={random_tailwind_color()} />
  <Icon.PauseSolid size="40" class={random_tailwind_color()} />
  <Icon.PenNibSolid size="40" class={random_tailwind_color()} />
  <Icon.PenSolid size="40" class={random_tailwind_color()} />
  <Icon.PenToSquareSolid size="40" class={random_tailwind_color()} />
  <Icon.PhoneSolid size="40" class={random_tailwind_color()} />
  <Icon.PlaySolid size="40" class={random_tailwind_color()} />
  <Icon.PlusSolid size="40" class={random_tailwind_color()} />
  <Icon.PrintSolid size="40" class={random_tailwind_color()} />
  <Icon.QuestionCircleSolid size="40" class={random_tailwind_color()} />
  <Icon.QuoteSolid size="40" class={random_tailwind_color()} />
  <Icon.ReceiptSolid size="40" class={random_tailwind_color()} />
  <Icon.RectangleListSolid size="40" class={random_tailwind_color()} />
  <Icon.ReplyAllSolid size="40" class={random_tailwind_color()} />
  <Icon.RestoreWindowSolid size="40" class={random_tailwind_color()} />
  <Icon.RocketSolid size="40" class={random_tailwind_color()} />
  <Icon.RulerCombinedSolid size="40" class={random_tailwind_color()} />
  <Icon.SalePercentSolid size="40" class={random_tailwind_color()} />
  <Icon.ScaleBalanceSolid size="40" class={random_tailwind_color()} />
  <Icon.SearchSolid size="40" class={random_tailwind_color()} />
  <Icon.ShareAllSolid size="40" class={random_tailwind_color()} />
  <Icon.ShareNodesSolid size="40" class={random_tailwind_color()} />
  <Icon.ShieldSolid size="40" class={random_tailwind_color()} />
  <Icon.ShoppingCartSolid size="40" class={random_tailwind_color()} />
  <Icon.ShuffleSolid size="40" class={random_tailwind_color()} />
  <Icon.SortHorizontalSolid size="40" class={random_tailwind_color()} />
  <Icon.SortVerticalSolid size="40" class={random_tailwind_color()} />
  <Icon.StackoverflowSolid size="40" class={random_tailwind_color()} />
  <Icon.StarHalfSolid size="40" class={random_tailwind_color()} />
  <Icon.StarHalfStrokeSolid size="40" class={random_tailwind_color()} />
  <Icon.StarSolid size="40" class={random_tailwind_color()} />
  <Icon.StoreSolid size="40" class={random_tailwind_color()} />
  <Icon.SunSolid size="40" class={random_tailwind_color()} />
  <Icon.SwatchbookSolid size="40" class={random_tailwind_color()} />
  <Icon.TableColumnSolid size="40" class={random_tailwind_color()} />
  <Icon.TableSolid size="40" class={random_tailwind_color()} />
  <Icon.TabletSolid size="40" class={random_tailwind_color()} />
  <Icon.TagSolid size="40" class={random_tailwind_color()} />
  <Icon.TerminalSolid size="40" class={random_tailwind_color()} />
  <Icon.TextCenterSolid size="40" class={random_tailwind_color()} />
  <Icon.TicketSolid size="40" class={random_tailwind_color()} />
  <Icon.TrashBinSolid size="40" class={random_tailwind_color()} />
  <Icon.TruckSolid size="40" class={random_tailwind_color()} />
  <Icon.TumbDownSolid size="40" class={random_tailwind_color()} />
  <Icon.TumbUpSolid size="40" class={random_tailwind_color()} />
  <Icon.TwitterSolid size="40" class={random_tailwind_color()} />
  <Icon.UnderlineSolid size="40" class={random_tailwind_color()} />
  <Icon.UploadSolid size="40" class={random_tailwind_color()} />
  <Icon.UserCircleSolid size="40" class={random_tailwind_color()} />
  <Icon.UserEditSolid size="40" class={random_tailwind_color()} />
  <Icon.UserGroupSolid size="40" class={random_tailwind_color()} />
  <Icon.UserHeadsetSolid size="40" class={random_tailwind_color()} />
  <Icon.UserPlusSolid size="40" class={random_tailwind_color()} />
  <Icon.UserRemoveSolid size="40" class={random_tailwind_color()} />
  <Icon.UserSettingsSolid size="40" class={random_tailwind_color()} />
  <Icon.UserSolid size="40" class={random_tailwind_color()} />
  <Icon.UsersSolid size="40" class={random_tailwind_color()} />
  <Icon.VideoSolid size="40" class={random_tailwind_color()} />
  <Icon.VolumeDownSolid size="40" class={random_tailwind_color()} />
  <Icon.VolumeUpSolid size="40" class={random_tailwind_color()} />
  <Icon.WalletSolid size="40" class={random_tailwind_color()} />
  <Icon.WandSparklesSolid size="40" class={random_tailwind_color()} />
  <Icon.WindowSolid size="40" class={random_tailwind_color()} />
  <Icon.YoutubeSolid size="40" class={random_tailwind_color()} />
  <Icon.ZoomInSolid size="40" class={random_tailwind_color()} />
  <Icon.ZoomOutSolid size="40" class={random_tailwind_color()} />
</div>
