<script>
  import * as Icon from '$lib';
  import DarkMode from 'flowbite-svelte/DarkMode.svelte';
  const random_tailwind_color = () => {
    const colors = ['primary', 'red', 'yellow', 'green', 'blue', 'indigo', 'purple', 'pink'];
    const shades = ['300', '400', '500'];
    const randomColor = colors[Math.floor(Math.random() * colors.length)];
    const randomShade = shades[Math.floor(Math.random() * shades.length)];
    return `text-${randomColor}-${randomShade} dark:text-${randomColor}-${randomShade} inline m-1`;
  };
</script>

<DarkMode />
<div class="p-8">
  <Icon.AddressCardSolid size="md" class={random_tailwind_color()} />
  <Icon.AdjustmentsHorizontalSolid size="md" class={random_tailwind_color()} />
  <Icon.AdjustmentsVerticalSolid size="md" class={random_tailwind_color()} />
  <Icon.AdressBookSolid size="md" class={random_tailwind_color()} />
  <Icon.AngleDownSolid size="md" class={random_tailwind_color()} />
  <Icon.AngleLeftSolid size="md" class={random_tailwind_color()} />
  <Icon.AngleRightSolid size="md" class={random_tailwind_color()} />
  <Icon.AngleUpSolid size="md" class={random_tailwind_color()} />
  <Icon.AnnotationSolid size="md" class={random_tailwind_color()} />
  <Icon.ArchiveSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowDownSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowDownToBraketSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowLeftSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowRightFromBracketSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowRightSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowRightToBracketSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowSortLettersSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowUpDownSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowUpRightSquareSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowUpSolid size="md" class={random_tailwind_color()} />
  <Icon.ArrowsRepeat1Solid size="md" class={random_tailwind_color()} />
  <Icon.ArrowsRepeatSolid size="md" class={random_tailwind_color()} />
  <Icon.AtomSolid size="md" class={random_tailwind_color()} />
  <Icon.BackwardStepSolid size="md" class={random_tailwind_color()} />
  <Icon.BadgeCheckSolid size="md" class={random_tailwind_color()} />
  <Icon.BagSolid size="md" class={random_tailwind_color()} />
  <Icon.BarsSolid size="md" class={random_tailwind_color()} />
  <Icon.BellActiveAltSolid size="md" class={random_tailwind_color()} />
  <Icon.BellActiveSolid size="md" class={random_tailwind_color()} />
  <Icon.BellRingSolid size="md" class={random_tailwind_color()} />
  <Icon.BellSolid size="md" class={random_tailwind_color()} />
  <Icon.BlenderPhoneSolid size="md" class={random_tailwind_color()} />
  <Icon.BoldSolid size="md" class={random_tailwind_color()} />
  <Icon.BookSolid size="md" class={random_tailwind_color()} />
  <Icon.BookmarkSolid size="md" class={random_tailwind_color()} />
  <Icon.BrainSolid size="md" class={random_tailwind_color()} />
  <Icon.BriefcaseSolid size="md" class={random_tailwind_color()} />
  <Icon.BugSolid size="md" class={random_tailwind_color()} />
  <Icon.BullhornSolid size="md" class={random_tailwind_color()} />
  <Icon.CalendarEditSolid size="md" class={random_tailwind_color()} />
  <Icon.CalendarMonthSolid size="md" class={random_tailwind_color()} />
  <Icon.CalendarWeekSolid size="md" class={random_tailwind_color()} />
  <Icon.CameraFotoSolid size="md" class={random_tailwind_color()} />
  <Icon.CaptioningSolid size="md" class={random_tailwind_color()} />
  <Icon.CaretDownSolid size="md" class={random_tailwind_color()} />
  <Icon.CaretLeftSolid size="md" class={random_tailwind_color()} />
  <Icon.CaretRightSolid size="md" class={random_tailwind_color()} />
  <Icon.CaretSortSolid size="md" class={random_tailwind_color()} />
  <Icon.CaretUpSolid size="md" class={random_tailwind_color()} />
  <Icon.CartPlusAltSolid size="md" class={random_tailwind_color()} />
  <Icon.CartPlusSolid size="md" class={random_tailwind_color()} />
  <Icon.CashSolid size="md" class={random_tailwind_color()} />
  <Icon.ChartLineDownSolid size="md" class={random_tailwind_color()} />
  <Icon.ChartLineUpSolid size="md" class={random_tailwind_color()} />
  <Icon.ChartMixedSolid size="md" class={random_tailwind_color()} />
  <Icon.ChartPieSolid size="md" class={random_tailwind_color()} />
  <Icon.ChartSolid size="md" class={random_tailwind_color()} />
  <Icon.CheckCircleSolid size="md" class={random_tailwind_color()} />
  <Icon.CheckSolid size="md" class={random_tailwind_color()} />
  <Icon.ChervonDoubleDownSolid size="md" class={random_tailwind_color()} />
  <Icon.ChervonDoubleLeftSolid size="md" class={random_tailwind_color()} />
  <Icon.ChervonDoubleRightSolid size="md" class={random_tailwind_color()} />
  <Icon.ChervonDoubleUpSolid size="md" class={random_tailwind_color()} />
  <Icon.ChevronDownSolid size="md" class={random_tailwind_color()} />
  <Icon.ChevronLeftSolid size="md" class={random_tailwind_color()} />
  <Icon.ChevronRightSolid size="md" class={random_tailwind_color()} />
  <Icon.ChevronSortSolid size="md" class={random_tailwind_color()} />
  <Icon.ChevronUpSolid size="md" class={random_tailwind_color()} />
  <Icon.ClapperboardPlaySolid size="md" class={random_tailwind_color()} />
  <Icon.ClipboardCheckSolid size="md" class={random_tailwind_color()} />
  <Icon.ClipboardListSolid size="md" class={random_tailwind_color()} />
  <Icon.ClipboardSolid size="md" class={random_tailwind_color()} />
  <Icon.ClockSolid size="md" class={random_tailwind_color()} />
  <Icon.CloneSolid size="md" class={random_tailwind_color()} />
  <Icon.CloseCircleSolid size="md" class={random_tailwind_color()} />
  <Icon.CloseSolid size="md" class={random_tailwind_color()} />
  <Icon.CloudArrowUpSolid size="md" class={random_tailwind_color()} />
  <Icon.CodeBranchSolid size="md" class={random_tailwind_color()} />
  <Icon.CodeForkSolid size="md" class={random_tailwind_color()} />
  <Icon.CodeMergeSolid size="md" class={random_tailwind_color()} />
  <Icon.CodePullRequestSolid size="md" class={random_tailwind_color()} />
  <Icon.CodeSolid size="md" class={random_tailwind_color()} />
  <Icon.CompressSolid size="md" class={random_tailwind_color()} />
  <Icon.ComputerSpeakerSolid size="md" class={random_tailwind_color()} />
  <Icon.CopySolid size="md" class={random_tailwind_color()} />
  <Icon.CotateSolid size="md" class={random_tailwind_color()} />
  <Icon.CreditCardSolid size="md" class={random_tailwind_color()} />
  <Icon.DatabaseSolid size="md" class={random_tailwind_color()} />
  <Icon.DesktopPcSolid size="md" class={random_tailwind_color()} />
  <Icon.DiscordSolid size="md" class={random_tailwind_color()} />
  <Icon.DnaSolid size="md" class={random_tailwind_color()} />
  <Icon.DollarSolid size="md" class={random_tailwind_color()} />
  <Icon.DownloadSolid size="md" class={random_tailwind_color()} />
  <Icon.DrawSquareSolid size="md" class={random_tailwind_color()} />
  <Icon.DribbbleSolid size="md" class={random_tailwind_color()} />
  <Icon.DropboxSolid size="md" class={random_tailwind_color()} />
  <Icon.EllipseHorizontalSolid size="md" class={random_tailwind_color()} />
  <Icon.EllipseVerticalSolid size="md" class={random_tailwind_color()} />
  <Icon.EnvelopeOpenSolid size="md" class={random_tailwind_color()} />
  <Icon.EnvelopeSolid size="md" class={random_tailwind_color()} />
  <Icon.EuroSolid size="md" class={random_tailwind_color()} />
  <Icon.ExclamationCircleSolid size="md" class={random_tailwind_color()} />
  <Icon.ExpandSolid size="md" class={random_tailwind_color()} />
  <Icon.EyeSlashSolid size="md" class={random_tailwind_color()} />
  <Icon.EyeSolid size="md" class={random_tailwind_color()} />
  <Icon.FaceGrinSolid size="md" class={random_tailwind_color()} />
  <Icon.FaceLaughSolid size="md" class={random_tailwind_color()} />
  <Icon.FaceMindBlowSolid size="md" class={random_tailwind_color()} />
  <Icon.FaceStarStruckSolid size="md" class={random_tailwind_color()} />
  <Icon.FacebookSolid size="md" class={random_tailwind_color()} />
  <Icon.FileChartBarSolid size="md" class={random_tailwind_color()} />
  <Icon.FileCheckSolid size="md" class={random_tailwind_color()} />
  <Icon.FileCodeSolid size="md" class={random_tailwind_color()} />
  <Icon.FileCopySolid size="md" class={random_tailwind_color()} />
  <Icon.FileCsvSolid size="md" class={random_tailwind_color()} />
  <Icon.FileEditSolid size="md" class={random_tailwind_color()} />
  <Icon.FileExportSolid size="md" class={random_tailwind_color()} />
  <Icon.FileImageSolid size="md" class={random_tailwind_color()} />
  <Icon.FileImportSolid size="md" class={random_tailwind_color()} />
  <Icon.FileLinesSolid size="md" class={random_tailwind_color()} />
  <Icon.FileMusicSolid size="md" class={random_tailwind_color()} />
  <Icon.FilePasteSolid size="md" class={random_tailwind_color()} />
  <Icon.FilePdfSolid size="md" class={random_tailwind_color()} />
  <Icon.FilePlusSolid size="md" class={random_tailwind_color()} />
  <Icon.FilePowerpointSolid size="md" class={random_tailwind_color()} />
  <Icon.FileShieldSolid size="md" class={random_tailwind_color()} />
  <Icon.FileSolid size="md" class={random_tailwind_color()} />
  <Icon.FileVideoSolid size="md" class={random_tailwind_color()} />
  <Icon.FileWordpressSolid size="md" class={random_tailwind_color()} />
  <Icon.FileZipperSolid size="md" class={random_tailwind_color()} />
  <Icon.FilterSolid size="md" class={random_tailwind_color()} />
  <Icon.FingerprintSolid size="md" class={random_tailwind_color()} />
  <Icon.FireSolid size="md" class={random_tailwind_color()} />
  <Icon.FolderDuplicateSolid size="md" class={random_tailwind_color()} />
  <Icon.FolderOpenSolid size="md" class={random_tailwind_color()} />
  <Icon.FolderPlusSolid size="md" class={random_tailwind_color()} />
  <Icon.FolderSolid size="md" class={random_tailwind_color()} />
  <Icon.ForwardSolid size="md" class={random_tailwind_color()} />
  <Icon.ForwardStepSolid size="md" class={random_tailwind_color()} />
  <Icon.GearSolid size="md" class={random_tailwind_color()} />
  <Icon.GiftBoxSolid size="md" class={random_tailwind_color()} />
  <Icon.GithubSolid size="md" class={random_tailwind_color()} />
  <Icon.GlobeSolid size="md" class={random_tailwind_color()} />
  <Icon.GoogleSolid size="md" class={random_tailwind_color()} />
  <Icon.GridPlusSolid size="md" class={random_tailwind_color()} />
  <Icon.GridSolid size="md" class={random_tailwind_color()} />
  <Icon.HeadphonesSolid size="md" class={random_tailwind_color()} />
  <Icon.HeartSolid size="md" class={random_tailwind_color()} />
  <Icon.HomeSolid size="md" class={random_tailwind_color()} />
  <Icon.HourglassSolid size="md" class={random_tailwind_color()} />
  <Icon.ImageSolid size="md" class={random_tailwind_color()} />
  <Icon.InboxFullSolid size="md" class={random_tailwind_color()} />
  <Icon.InboxSolid size="md" class={random_tailwind_color()} />
  <Icon.InfoCircleSolid size="md" class={random_tailwind_color()} />
  <Icon.ItalicSolid size="md" class={random_tailwind_color()} />
  <Icon.KeyboardSolid size="md" class={random_tailwind_color()} />
  <Icon.LandmarkSolid size="md" class={random_tailwind_color()} />
  <Icon.LayersSolid size="md" class={random_tailwind_color()} />
  <Icon.LifeBuoySolid size="md" class={random_tailwind_color()} />
  <Icon.LinkSolid size="md" class={random_tailwind_color()} />
  <Icon.LinkedinSolid size="md" class={random_tailwind_color()} />
  <Icon.ListMusicSolid size="md" class={random_tailwind_color()} />
  <Icon.ListOrdoredSolid size="md" class={random_tailwind_color()} />
  <Icon.ListSolid size="md" class={random_tailwind_color()} />
  <Icon.LockOpenSolid size="md" class={random_tailwind_color()} />
  <Icon.LockSolid size="md" class={random_tailwind_color()} />
  <Icon.MailBoxSolid size="md" class={random_tailwind_color()} />
  <Icon.MapPinAltSolid size="md" class={random_tailwind_color()} />
  <Icon.MapPinSolid size="md" class={random_tailwind_color()} />
  <Icon.MessageCaptionSolid size="md" class={random_tailwind_color()} />
  <Icon.MessagesSolid size="md" class={random_tailwind_color()} />
  <Icon.MicrophoneSolid size="md" class={random_tailwind_color()} />
  <Icon.MinimizeSolid size="md" class={random_tailwind_color()} />
  <Icon.MinusSolid size="md" class={random_tailwind_color()} />
  <Icon.MobilePhoneSolid size="md" class={random_tailwind_color()} />
  <Icon.MoonSolid size="md" class={random_tailwind_color()} />
  <Icon.NewspaperSolid size="md" class={random_tailwind_color()} />
  <Icon.OpenBookSolid size="md" class={random_tailwind_color()} />
  <Icon.PalleteSolid size="md" class={random_tailwind_color()} />
  <Icon.PapperClipSolid size="md" class={random_tailwind_color()} />
  <Icon.PapperPlaneSolid size="md" class={random_tailwind_color()} />
  <Icon.PauseSolid size="md" class={random_tailwind_color()} />
  <Icon.PenNibSolid size="md" class={random_tailwind_color()} />
  <Icon.PenSolid size="md" class={random_tailwind_color()} />
  <Icon.PenToSquareSolid size="md" class={random_tailwind_color()} />
  <Icon.PhoneSolid size="md" class={random_tailwind_color()} />
  <Icon.PlaySolid size="md" class={random_tailwind_color()} />
  <Icon.PlusSolid size="md" class={random_tailwind_color()} />
  <Icon.PrintSolid size="md" class={random_tailwind_color()} />
  <Icon.QuestionCircleSolid size="md" class={random_tailwind_color()} />
  <Icon.QuoteSolid size="md" class={random_tailwind_color()} />
  <Icon.ReceiptSolid size="md" class={random_tailwind_color()} />
  <Icon.RectangleListSolid size="md" class={random_tailwind_color()} />
  <Icon.ReplyAllSolid size="md" class={random_tailwind_color()} />
  <Icon.RestoreWindowSolid size="md" class={random_tailwind_color()} />
  <Icon.RocketSolid size="md" class={random_tailwind_color()} />
  <Icon.RulerCombinedSolid size="md" class={random_tailwind_color()} />
  <Icon.SalePercentSolid size="md" class={random_tailwind_color()} />
  <Icon.ScaleBalanceSolid size="md" class={random_tailwind_color()} />
  <Icon.SearchSolid size="md" class={random_tailwind_color()} />
  <Icon.ShareAllSolid size="md" class={random_tailwind_color()} />
  <Icon.ShareNodesSolid size="md" class={random_tailwind_color()} />
  <Icon.ShieldSolid size="md" class={random_tailwind_color()} />
  <Icon.ShoppingCartSolid size="md" class={random_tailwind_color()} />
  <Icon.ShuffleSolid size="md" class={random_tailwind_color()} />
  <Icon.SortHorizontalSolid size="md" class={random_tailwind_color()} />
  <Icon.SortVerticalSolid size="md" class={random_tailwind_color()} />
  <Icon.StackoverflowSolid size="md" class={random_tailwind_color()} />
  <Icon.StarHalfSolid size="md" class={random_tailwind_color()} />
  <Icon.StarHalfStrokeSolid size="md" class={random_tailwind_color()} />
  <Icon.StarSolid size="md" class={random_tailwind_color()} />
  <Icon.StoreSolid size="md" class={random_tailwind_color()} />
  <Icon.SunSolid size="md" class={random_tailwind_color()} />
  <Icon.SwatchbookSolid size="md" class={random_tailwind_color()} />
  <Icon.TableColumnSolid size="md" class={random_tailwind_color()} />
  <Icon.TableSolid size="md" class={random_tailwind_color()} />
  <Icon.TabletSolid size="md" class={random_tailwind_color()} />
  <Icon.TagSolid size="md" class={random_tailwind_color()} />
  <Icon.TerminalSolid size="md" class={random_tailwind_color()} />
  <Icon.TextCenterSolid size="md" class={random_tailwind_color()} />
  <Icon.ThumbsDownSolid size="md" class={random_tailwind_color()} />
  <Icon.ThumbsUpSolid size="md" class={random_tailwind_color()} />
  <Icon.TicketSolid size="md" class={random_tailwind_color()} />
  <Icon.TrashBinSolid size="md" class={random_tailwind_color()} />
  <Icon.TruckSolid size="md" class={random_tailwind_color()} />
  <Icon.TwitterSolid size="md" class={random_tailwind_color()} />
  <Icon.UnderlineSolid size="md" class={random_tailwind_color()} />
  <Icon.UploadSolid size="md" class={random_tailwind_color()} />
  <Icon.UserCircleSolid size="md" class={random_tailwind_color()} />
  <Icon.UserEditSolid size="md" class={random_tailwind_color()} />
  <Icon.UserGroupSolid size="md" class={random_tailwind_color()} />
  <Icon.UserHeadsetSolid size="md" class={random_tailwind_color()} />
  <Icon.UserPlusSolid size="md" class={random_tailwind_color()} />
  <Icon.UserRemoveSolid size="md" class={random_tailwind_color()} />
  <Icon.UserSettingsSolid size="md" class={random_tailwind_color()} />
  <Icon.UserSolid size="md" class={random_tailwind_color()} />
  <Icon.UsersSolid size="md" class={random_tailwind_color()} />
  <Icon.VideoSolid size="md" class={random_tailwind_color()} />
  <Icon.VolumeDownSolid size="md" class={random_tailwind_color()} />
  <Icon.VolumeUpSolid size="md" class={random_tailwind_color()} />
  <Icon.WalletSolid size="md" class={random_tailwind_color()} />
  <Icon.WandSparklesSolid size="md" class={random_tailwind_color()} />
  <Icon.WindowSolid size="md" class={random_tailwind_color()} />
  <Icon.YoutubeSolid size="md" class={random_tailwind_color()} />
  <Icon.ZoomInSolid size="md" class={random_tailwind_color()} />
  <Icon.ZoomOutSolid size="md" class={random_tailwind_color()} />
</div>
