<script>
  import * as Icon from '$lib';
  let myClass = "inline m-1"
</script>

<div class="p-8">
  <Icon.AdjustmentsHorizontalOutline size="40" class={myClass} />
  <Icon.AdjustmentsVerticalOutline size="40" class={myClass} />
  <Icon.AdressBookOutline size="40" class={myClass} />
  <Icon.AlignCenterOutline size="40" class={myClass} />
  <Icon.AngleDownOutline size="40" class={myClass} />
  <Icon.AngleLeftOutline size="40" class={myClass} />
  <Icon.AngleRightOutline size="40" class={myClass} />
  <Icon.AngleTopOutline size="40" class={myClass} />
  <Icon.AnnotationOutline size="40" class={myClass} />
  <Icon.ArchiveOutline size="40" class={myClass} />
  <Icon.ArrowDownOutline size="40" class={myClass} />
  <Icon.ArrowDownToBracketOutline size="40" class={myClass} />
  <Icon.ArrowLeftOutline size="40" class={myClass} />
  <Icon.ArrowLeftToBracketOutline size="40" class={myClass} />
  <Icon.ArrowRightArrowLeftOutline size="40" class={myClass} />
  <Icon.ArrowRightOutline size="40" class={myClass} />
  <Icon.ArrowRightToBracketOutline size="40" class={myClass} />
  <Icon.ArrowSortLettersOutline size="40" class={myClass} />
  <Icon.ArrowUpDownOutline size="40" class={myClass} />
  <Icon.ArrowUpOutline size="40" class={myClass} />
  <Icon.ArrowUpRightFromSquareOutline size="40" class={myClass} />
  <Icon.ArrowsRepeat1Outline size="40" class={myClass} />
  <Icon.ArrowsRepeatOutline size="40" class={myClass} />
  <Icon.AtomOutline size="40" class={myClass} />
  <Icon.BackwardStepOutline size="40" class={myClass} />
  <Icon.BadgeCheckOutline size="40" class={myClass} />
  <Icon.BarsOutline size="40" class={myClass} />
  <Icon.BellActiveAltOutline size="40" class={myClass} />
  <Icon.BellActiveOutline size="40" class={myClass} />
  <Icon.BellOutline size="40" class={myClass} />
  <Icon.BellRingOutline size="40" class={myClass} />
  <Icon.BlenderPhoneOutline size="40" class={myClass} />
  <Icon.BookOpenOutline size="40" class={myClass} />
  <Icon.BookOutline size="40" class={myClass} />
  <Icon.BookmarkOutline size="40" class={myClass} />
  <Icon.BrainOutline size="40" class={myClass} />
  <Icon.BriefcaseOutline size="40" class={myClass} />
  <Icon.BugOutline size="40" class={myClass} />
  <Icon.BullhornOutline size="40" class={myClass} />
  <Icon.CalendarEditOutline size="40" class={myClass} />
  <Icon.CalendarMonthOutline size="40" class={myClass} />
  <Icon.CalendarWeekOutline size="40" class={myClass} />
  <Icon.CameraFotoOutline size="40" class={myClass} />
  <Icon.CaptioningOutline size="40" class={myClass} />
  <Icon.CaretDownOutline size="40" class={myClass} />
  <Icon.CaretLeftOutline size="40" class={myClass} />
  <Icon.CaretRightOutline size="40" class={myClass} />
  <Icon.CaretSortOutline size="40" class={myClass} />
  <Icon.CaretUpOutline size="40" class={myClass} />
  <Icon.CartOutline size="40" class={myClass} />
  <Icon.CartPlusAltOutline size="40" class={myClass} />
  <Icon.CartPlusOutline size="40" class={myClass} />
  <Icon.CashOutline size="40" class={myClass} />
  <Icon.ChartLineUpOutline size="40" class={myClass} />
  <Icon.ChartMixedOutline size="40" class={myClass} />
  <Icon.ChartOutline size="40" class={myClass} />
  <Icon.ChartPieOutline size="40" class={myClass} />
  <Icon.CheckCircleOutline size="40" class={myClass} />
  <Icon.CheckOutline size="40" class={myClass} />
  <Icon.ChevronDoubleDownOutline size="40" class={myClass} />
  <Icon.ChevronDoubleLeftOutline size="40" class={myClass} />
  <Icon.ChevronDoubleRightOutline size="40" class={myClass} />
  <Icon.ChevronDoubleUpOutline size="40" class={myClass} />
  <Icon.ChevronDownOutline size="40" class={myClass} />
  <Icon.ChevronLeftOutline size="40" class={myClass} />
  <Icon.ChevronRightOutline size="40" class={myClass} />
  <Icon.ChevronSortOutline size="40" class={myClass} />
  <Icon.ChevronUpOutline size="40" class={myClass} />
  <Icon.ClapperboardPlayOutline size="40" class={myClass} />
  <Icon.ClipboardCheckOutline size="40" class={myClass} />
  <Icon.ClipboardListOutline size="40" class={myClass} />
  <Icon.ClipboardOutline size="40" class={myClass} />
  <Icon.ClockOutline size="40" class={myClass} />
  <Icon.CloseOutline size="40" class={myClass} />
  <Icon.CloudArrowUpOutline size="40" class={myClass} />
  <Icon.CodeBranchOutline size="40" class={myClass} />
  <Icon.CodeForkOutline size="40" class={myClass} />
  <Icon.CodeMergeOutline size="40" class={myClass} />
  <Icon.CodeOutline size="40" class={myClass} />
  <Icon.CodePullRequestOutline size="40" class={myClass} />
  <Icon.CogOutline size="40" class={myClass} />
  <Icon.CompressOutline size="40" class={myClass} />
  <Icon.ComputerSpeakerOutline size="40" class={myClass} />
  <Icon.CreditCardOutline size="40" class={myClass} />
  <Icon.DatabaseOutline size="40" class={myClass} />
  <Icon.DesktopPcOutline size="40" class={myClass} />
  <Icon.DnaOutline size="40" class={myClass} />
  <Icon.DollarOutline size="40" class={myClass} />
  <Icon.DotsHorizontalOutline size="40" class={myClass} />
  <Icon.DotsVerticalOutline size="40" class={myClass} />
  <Icon.DownloadOutline size="40" class={myClass} />
  <Icon.DrawSquareOutline size="40" class={myClass} />
  <Icon.EditOutline size="40" class={myClass} />
  <Icon.EnvelopeOpenOutline size="40" class={myClass} />
  <Icon.EnvelopeOutline size="40" class={myClass} />
  <Icon.EuroOutline size="40" class={myClass} />
  <Icon.ExclamationCircleOutline size="40" class={myClass} />
  <Icon.ExpandOutline size="40" class={myClass} />
  <Icon.EyeOutline size="40" class={myClass} />
  <Icon.EyeSlashOutline size="40" class={myClass} />
  <Icon.FaceExplodeOutline size="40" class={myClass} />
  <Icon.FaceGrinOutline size="40" class={myClass} />
  <Icon.FaceGrinStarsOutline size="40" class={myClass} />
  <Icon.FaceLaughOutline size="40" class={myClass} />
  <Icon.FileChartBarOutline size="40" class={myClass} />
  <Icon.FileCheckOutline size="40" class={myClass} />
  <Icon.FileCirclePlusOutline size="40" class={myClass} />
  <Icon.FileCloneOutline size="40" class={myClass} />
  <Icon.FileCodeOutline size="40" class={myClass} />
  <Icon.FileCopyOutline size="40" class={myClass} />
  <Icon.FileCsvOutline size="40" class={myClass} />
  <Icon.FileExportOutline size="40" class={myClass} />
  <Icon.FileImageOutline size="40" class={myClass} />
  <Icon.FileImportOutline size="40" class={myClass} />
  <Icon.FileLinesOutline size="40" class={myClass} />
  <Icon.FileMusicOutline size="40" class={myClass} />
  <Icon.FileOutline size="40" class={myClass} />
  <Icon.FilePasteOutline size="40" class={myClass} />
  <Icon.FilePdfOutline size="40" class={myClass} />
  <Icon.FilePenOutline size="40" class={myClass} />
  <Icon.FilePptOutline size="40" class={myClass} />
  <Icon.FileShieldOutline size="40" class={myClass} />
  <Icon.FileVideoOutline size="40" class={myClass} />
  <Icon.FileWordOutline size="40" class={myClass} />
  <Icon.FileZipOutline size="40" class={myClass} />
  <Icon.FilterOutline size="40" class={myClass} />
  <Icon.FingerprintOutline size="40" class={myClass} />
  <Icon.FireOutline size="40" class={myClass} />
  <Icon.FolderDuplicateOutline size="40" class={myClass} />
  <Icon.FolderOpenOutline size="40" class={myClass} />
  <Icon.FolderOutline size="40" class={myClass} />
  <Icon.FolderPlusOutline size="40" class={myClass} />
  <Icon.ForwardOutline size="40" class={myClass} />
  <Icon.ForwardStepOutline size="40" class={myClass} />
  <Icon.GiftBoxOutline size="40" class={myClass} />
  <Icon.GlobeOutline size="40" class={myClass} />
  <Icon.GridOutline size="40" class={myClass} />
  <Icon.GridPlusOutline size="40" class={myClass} />
  <Icon.HeadphonesOutline size="40" class={myClass} />
  <Icon.HeartOutline size="40" class={myClass} />
  <Icon.HomeOutline size="40" class={myClass} />
  <Icon.HourglassOutline size="40" class={myClass} />
  <Icon.ImageOutline size="40" class={myClass} />
  <Icon.InboxFullOutline size="40" class={myClass} />
  <Icon.InboxOutline size="40" class={myClass} />
  <Icon.InfoCircleOutline size="40" class={myClass} />
  <Icon.KeyboardOutline size="40" class={myClass} />
  <Icon.LandmarkOutline size="40" class={myClass} />
  <Icon.LayersOutline size="40" class={myClass} />
  <Icon.LetterBoldOutline size="40" class={myClass} />
  <Icon.LetterItalicOutline size="40" class={myClass} />
  <Icon.LetterUnderlineOutline size="40" class={myClass} />
  <Icon.LifeBuoyOutline size="40" class={myClass} />
  <Icon.LinkOutline size="40" class={myClass} />
  <Icon.ListMusicOutline size="40" class={myClass} />
  <Icon.ListOutline size="40" class={myClass} />
  <Icon.LockOpenOutline size="40" class={myClass} />
  <Icon.LockOutline size="40" class={myClass} />
  <Icon.MailBoxOutline size="40" class={myClass} />
  <Icon.MapLocationOutline size="40" class={myClass} />
  <Icon.MapPinOutline size="40" class={myClass} />
  <Icon.MessageCaptionOutline size="40" class={myClass} />
  <Icon.MessageDotsOutline size="40" class={myClass} />
  <Icon.MessagesOutline size="40" class={myClass} />
  <Icon.MicrophoneOutline size="40" class={myClass} />
  <Icon.MinimizeOutline size="40" class={myClass} />
  <Icon.MinusOutline size="40" class={myClass} />
  <Icon.MobilePhoneOutline size="40" class={myClass} />
  <Icon.MoonOutline size="40" class={myClass} />
  <Icon.NewspapperOutline size="40" class={myClass} />
  <Icon.OrdoredListOutline size="40" class={myClass} />
  <Icon.PaletteOutline size="40" class={myClass} />
  <Icon.PaperClipOutline size="40" class={myClass} />
  <Icon.PapperPlaneOutline size="40" class={myClass} />
  <Icon.PauseOutline size="40" class={myClass} />
  <Icon.PenNibOutline size="40" class={myClass} />
  <Icon.PenOutline size="40" class={myClass} />
  <Icon.PhoneOutline size="40" class={myClass} />
  <Icon.PlayOutline size="40" class={myClass} />
  <Icon.PlusOutline size="40" class={myClass} />
  <Icon.PrinterOutline size="40" class={myClass} />
  <Icon.ProfileCardOutline size="40" class={myClass} />
  <Icon.QuestionCircleOutline size="40" class={myClass} />
  <Icon.QuoteOutline size="40" class={myClass} />
  <Icon.ReceiptOutline size="40" class={myClass} />
  <Icon.RectangleListOutline size="40" class={myClass} />
  <Icon.ReplyAllOutline size="40" class={myClass} />
  <Icon.RocketOutline size="40" class={myClass} />
  <Icon.RotateOutline size="40" class={myClass} />
  <Icon.RuleCombinedOutline size="40" class={myClass} />
  <Icon.SalePercentOutline size="40" class={myClass} />
  <Icon.ScaleBalancedOutline size="40" class={myClass} />
  <Icon.SearchOutline size="40" class={myClass} />
  <Icon.ShareAllOutline size="40" class={myClass} />
  <Icon.ShareNodesOutline size="40" class={myClass} />
  <Icon.ShieldOutline size="40" class={myClass} />
  <Icon.ShoppingBagOutline size="40" class={myClass} />
  <Icon.ShuffleOutline size="40" class={myClass} />
  <Icon.SortOutline size="40" class={myClass} />
  <Icon.StarHalfOutline size="40" class={myClass} />
  <Icon.StarHalfStrokeOutline size="40" class={myClass} />
  <Icon.StarOutline size="40" class={myClass} />
  <Icon.StoreOutline size="40" class={myClass} />
  <Icon.SunOutline size="40" class={myClass} />
  <Icon.SwatchbookOutline size="40" class={myClass} />
  <Icon.TableColumnOutline size="40" class={myClass} />
  <Icon.TableRowOutline size="40" class={myClass} />
  <Icon.TabletOutline size="40" class={myClass} />
  <Icon.TagOutline size="40" class={myClass} />
  <Icon.TerminalOutline size="40" class={myClass} />
  <Icon.ThumbsDownOutline size="40" class={myClass} />
  <Icon.ThumbsUpOutline size="40" class={myClass} />
  <Icon.TicketOutline size="40" class={myClass} />
  <Icon.TrashBinOutline size="40" class={myClass} />
  <Icon.TruckOutline size="40" class={myClass} />
  <Icon.UploadOutline size="40" class={myClass} />
  <Icon.UserAddOutline size="40" class={myClass} />
  <Icon.UserCircleOutline size="40" class={myClass} />
  <Icon.UserEditOutline size="40" class={myClass} />
  <Icon.UserHeadsetOutline size="40" class={myClass} />
  <Icon.UserOutline size="40" class={myClass} />
  <Icon.UserRemoveOutline size="40" class={myClass} />
  <Icon.UserSettingsOutline size="40" class={myClass} />
  <Icon.UsersGroupOutline size="40" class={myClass} />
  <Icon.UsersOutline size="40" class={myClass} />
  <Icon.VideoCameraOutline size="40" class={myClass} />
  <Icon.VolumeDownOutline size="40" class={myClass} />
  <Icon.VolumeUpOutline size="40" class={myClass} />
  <Icon.WalletOutline size="40" class={myClass} />
  <Icon.WandMagicSparklesOutline size="40" class={myClass} />
  <Icon.WindowOutline size="40" class={myClass} />
  <Icon.WindowRestoreOutline size="40" class={myClass} />
  <Icon.XCircleOutline size="40" class={myClass} />
  <Icon.ZoomInOutline size="40" class={myClass} />
  <Icon.ZoomOutOutline size="40" class={myClass} />
</div>
